CREATE TABLE public.OFFICES
(
  OFFICEID NUMERIC PRIMARY KEY NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  ADRESS VARCHAR(255),
  TEL VARCHAR(20)
);
CREATE SEQUENCE OFFICEID_SEQ MINVALUE 1 MAXVALUE 10000000000 START WITH 1 INCREMENT BY 1;