CREATE TABLE public.PRODUCTS
(
  ID        NUMERIC PRIMARY KEY NOT NULL,
  BATCH     VARCHAR(20)         NOT NULL,
  GOODSTYPE VARCHAR(20)         NOT NULL,
  DESCR      VARCHAR(200),
  KG        NUMERIC             NOT NULL,
  PX        NUMERIC             NOT NULL,
  CBD       NUMERIC             NOT NULL,
  THC       NUMERIC             NOT NULL,
  DATE      DATE                NOT NULL
);

CREATE SEQUENCE PRODUCTID_SEQ MINVALUE 1000 MAXVALUE 10000000000 START WITH 10001 INCREMENT BY 1;